# Generated by Django 5.0.4 on 2024-05-11 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approve_Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20, null=True)),
                ('smobile', models.BigIntegerField(null=True, unique=True)),
                ('semail', models.EmailField(max_length=254, null=True, unique=True)),
                ('slocation', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Pending_seller',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20, null=True)),
                ('smobile', models.BigIntegerField(null=True, unique=True)),
                ('semail', models.EmailField(max_length=254, null=True, unique=True)),
                ('slocation', models.CharField(max_length=20, null=True)),
                ('usertype', models.CharField(max_length=20)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sellersrtable',
            },
        ),
    ]
