# Generated by Django 5.0.4 on 2024-05-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=250)),
                ('model_name', models.CharField(max_length=250)),
                ('Features', models.TextField()),
                ('category', models.CharField(default='laptop', max_length=100)),
                ('price', models.FloatField()),
                ('stocks', models.IntegerField(choices=[(1, 'stock_in'), (0, 'stock_out')], default=0)),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'db_table': 'productstable',
            },
        ),
    ]
